### PR TITLE
Colorful icons

### PR DESCRIPTION
**Pull request by pcvera**
Dependent on https://github.com/cardinalitypuzzles/cardboard/pull/552

I feel less certain about the colorful icons being a good idea, so this PR is separate, pending some voting about whether we like them or not. If so, should be merged after #552 

Before
image

After
image

Dark Mode
image

### CODE REVIEW

**Comment by rgossiaux** [comment]
Can you fix the merge conflict stuff now that the other PR is merged?

**Comment by pcvera** [comment]
done

**Review by erwa — APPROVED** [review]
I also prefer the colored sheet and Discord icons.

Didn't realize the icons were SVGs. Hopefully rendering them when there's a lot of puzzles on the page isn't a performance issue

**Comment by pcvera** [comment]
Putting on my design hat, I think the lack of uniformity bugs me a bit.

That being said, I'm happy to be outvoted, shipping it.

**Pull request merged**
