### PR TITLE
Fix the backsolved tag/sheet renaming interaction

### PR DESCRIPTION
**Pull request by rgossiaux**
I broke this when I changed the casing of the default tags. Making this case-insensitive.

### CODE REVIEW

**Comment by rgossiaux** [comment]
Looks like the tests are broken here because GH actions are using sqlite so I made a PR to change that over.

**Review by rawxfish — APPROVED** [review]

**Comment by erwa** [comment]
> Looks like the tests are broken here because GH actions are using sqlite so I made a PR to change that over.

I'm guessing this is the failed run?: https://github.com/cardinalitypuzzles/cardboard/runs/4786213594?check_suite_focus=true

```
AssertionError: expected call not found.
Expected: delay(sheet_url='testsheet.com', name='[BACKSOLVED: ANS, ANS2] Test')
Actual: delay(sheet_url='testsheet.com', name='[SOLVED: ANS, ANS2] Test')
```

Do we know why it failed with sqlite but passed with Postgres? This doesn't involve the case-insensitive field so I'm surprised at the difference in behavior.

**Comment by erwa** [comment]
> This doesn't involve the case-insensitive field so I'm surprised at the difference in behavior.

Oh nvm, I just looked at the code and you are testing case-insensitive updates. That explains why

**Review by erwa — APPROVED** [review]
Nice. Thanks for adding tests!

**Pull request merged**
