### PR TITLE
improve performance of default puzzle tag population

### PR DESCRIPTION
**Pull request by rawxfish**
Old code was doing a separate db query for each `get_or_create` on each default tag.

### CODE REVIEW

**Review by erwa — APPROVED** [review]
Sure, though it looks like create_default_tags() is only called when a new hunt is created and then never again so not sure how much performance matters?

**Comment by rawxfish** [comment]
It's also called when you edit the hunt (it's sorta a hacky way to populate or de-populate the default tags)

**Comment by erwa** [comment]
Gotcha. Thanks for optimizing this!

**Review by rgossiaux — APPROVED** [review]

**Comment by erwa** [comment]
oh, btw, did you find this performance issue after enabling silk in #656?

**Comment by rawxfish** [comment]
yes

**Pull request merged**
