### PR TITLE
adds toggle for light and dark mode

### PR DESCRIPTION
**Pull request by rawxfish**
Light:

image

Dark:

image

### CODE REVIEW

**Comment by rgossiaux** [comment]
Hmm I feel like we might need to change a lot of the other colors with dark mode, this feels kinda painful to look at it (not that the normal UI is that pretty to begin with...)

**Review by erwa — APPROVED** [review]
Maybe ask some of the folks who requested dark mode to take a look at the screenshot and see what they think?

(I'm fine with what you've done so far; we can always tweak the colors further based on feedback.)

**Comment by rawxfish** [comment]
Hmm I didn't want to spend too much time tweaking colors, so I just went with the first templates I could find lol 

Alternatively, we can use some of the themes from https://bootswatch.com/ if you guys prefer those?

**Comment by rgossiaux** [comment]
> Hmm I didn't want to spend too much time tweaking colors, so I just went with the first templates I could find lol
> 
> Alternatively, we can use some of the themes from https://bootswatch.com/ if you guys prefer those?

Yeah, I guess we can try a couple of those and see if any of them look better?

**Comment by rawxfish** [comment]
I played around with the dark scenes from that... I think all of them would also require a lot of manual overrides. For now, I think we should just go with this, since it at least adds the toggle and makes it easier to do the overrides via the .bootstrap-dark class

**Pull request merged**
